### ISSUE TITLE
How to test a call on localhost?

### ISSUE THREAD

**Issue by orafaelfragoso** [mozilla/tincan#35]
I'm not really familiar with WebRTC yet but I'm using this project to learn it and I want to take care of #26 but I couldn't make a call yet on localhost.

Can you give me a direction so I can improve the docs and work on that issue?

**Comment by shane-tomlinson** [comment]
Hi @rafaelfragosom, Tincan was an experimental project that hasn't seen any activity in ~ 2 years. The original developer (@ryanseys) has since moved to another company. I'm not sure who to point you to that would still have context.

**Comment by ryanseys** [comment]
So tincan requires a persona instance to work properly. You should be able to point it at the production server and have it "just work" (TM) but I have not tested it for quite some time. Also I'm assuming that dependencies haven't grown out of date or webrtc hasn't changed its spec. You may wish to check the developer console in the browser and report here if you see any issues. That all being said, webrtc is very cool so I definitely suggest you try to build something yourself with it! Tincan was created as a demonstration /experiment in authenticating calls with persona, but that effort has since been put on hold.

**Comment by orafaelfragoso** [comment]
@shane-tomlinson I'm aware of this, just exercising the brain.
@ryanseys I'm gonna point it at production then, I'll let you know if it helps.

Thanks, guys!
